version: "3.7"

services:
  gpt_engineer:
    image: alpine:latest
    container_name: gpt_engineer
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./gpt_engineer:/gpt_engineer
    