version: "3.7"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gpt_engineer:
    image: alpine:latest
    container_name: gpt_engineer
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./gpt_engineer:/gpt_engineer
